const mongoose = require('mongoose');

const proposalTaskSchema = new mongoose.Schema(
  {
    proposal: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Proposal',
      required: true,
      index: true,
    },
    assignedTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    type: {
      type: String,
      enum: ['follow_up_negociacao'],
      default: 'follow_up_negociacao',
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 200,
    },
    notes: {
      type: String,
      trim: true,
      maxlength: 1000,
    },
    dueAt: {
      type: Date,
      default: null,
    },
    completedAt: {
      type: Date,
      default: null,
    },
    status: {
      type: String,
      enum: ['pending', 'completed', 'cancelled'],
      default: 'pending',
      index: true,
    },
    daysInNegotiation: {
      type: Number,
      min: 0,
    },
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
  },
  { timestamps: true }
);

proposalTaskSchema.index(
  { proposal: 1, type: 1, status: 1 },
  { partialFilterExpression: { status: 'pending', autoGenerated: true } }
);

module.exports = mongoose.model('ProposalTask', proposalTaskSchema);
