const Proposal = require('../models/Proposal');
const ProposalTask = require('../models/ProposalTask');
const Notification = require('../models/Notification');
const { DEFAULT_FOLLOWUP_DAYS } = require('../config/followUp');

function getFollowUpDaysThreshold() {
  const raw = process.env.PROPOSAL_FOLLOWUP_DAYS;
  const n = parseInt(raw, 10);
  if (Number.isFinite(n) && n > 0) return n;
  return DEFAULT_FOLLOWUP_DAYS;
}

function getDaysInNegotiation(proposal) {
  const ref = proposal.updatedAt || proposal.createdAt;
  const ms = Date.now() - new Date(ref).getTime();
  return Math.floor(ms / 86400000);
}

function getSellerUserId(proposal) {
  const s = proposal.seller;
  if (!s) return proposal.createdBy?.toString?.() || proposal.createdBy;
  if (s._id) return s._id.toString();
  return s.toString();
}

function getClientLabel(proposal) {
  const c = proposal.client;
  if (!c) return 'Cliente';
  return c.razaoSocial || c.company || c.name || 'Cliente';
}

/**
 * Varre propostas em negociação há X+ dias e cria tarefa + notificação (uma tarefa pendente por proposta).
 */
async function runProposalFollowUpScan() {
  const thresholdDays = getFollowUpDaysThreshold();
  const cutoff = new Date(Date.now() - thresholdDays * 86400000);

  const proposals = await Proposal.find({
    status: 'negociacao',
    $or: [{ updatedAt: { $lte: cutoff } }, { createdAt: { $lte: cutoff } }],
  })
    .select(
      'proposalNumber client seller createdBy status createdAt updatedAt total'
    )
    .lean();

  const results = {
    thresholdDays,
    scanned: proposals.length,
    tasksCreated: 0,
    notificationsCreated: 0,
    skipped: 0,
    errors: [],
  };

  for (const proposal of proposals) {
    try {
      const days = getDaysInNegotiation(proposal);
      if (days < thresholdDays) {
        results.skipped += 1;
        continue;
      }

      const existing = await ProposalTask.findOne({
        proposal: proposal._id,
        type: 'follow_up_negociacao',
        status: 'pending',
        autoGenerated: true,
      });

      if (existing) {
        results.skipped += 1;
        continue;
      }

      const assignedTo = getSellerUserId(proposal);
      if (!assignedTo) {
        results.skipped += 1;
        continue;
      }

      const clientName = getClientLabel(proposal);
      const title = `Follow-up: ${proposal.proposalNumber || 'Proposta'} — ${days} dias em negociação`;
      const dueAt = new Date();
      dueAt.setDate(dueAt.getDate() + 2);

      const task = await ProposalTask.create({
        proposal: proposal._id,
        assignedTo,
        type: 'follow_up_negociacao',
        title,
        notes: `Proposta em negociação há ${days} dias. Entre em contato com ${clientName} e atualize o status.`,
        dueAt,
        daysInNegotiation: days,
        autoGenerated: true,
        createdBy: null,
        status: 'pending',
      });

      results.tasksCreated += 1;

      await Notification.create({
        title: '⏰ Follow-up de proposta',
        message: `${proposal.proposalNumber || 'Proposta'} está há ${days} dias em negociação. Tarefa criada: retomar contato com ${clientName}.`,
        type: 'proposal_followup',
        priority: days >= thresholdDays * 2 ? 'high' : 'medium',
        recipient: assignedTo.toString(),
        sender: 'system',
        relatedEntity: proposal._id.toString(),
        relatedEntityType: 'proposal',
        data: {
          proposalId: proposal._id.toString(),
          proposalNumber: proposal.proposalNumber,
          taskId: task._id.toString(),
          daysInNegotiation: days,
          clientName,
        },
      });

      results.notificationsCreated += 1;
    } catch (err) {
      results.errors.push({
        proposalId: proposal._id?.toString(),
        message: err.message,
      });
    }
  }

  return results;
}

async function cancelPendingFollowUpTasks(proposalId) {
  await ProposalTask.updateMany(
    {
      proposal: proposalId,
      type: 'follow_up_negociacao',
      status: 'pending',
      autoGenerated: true,
    },
    { status: 'cancelled', completedAt: new Date() }
  );
}

module.exports = {
  getFollowUpDaysThreshold,
  getDaysInNegotiation,
  runProposalFollowUpScan,
  cancelPendingFollowUpTasks,
};
